name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper analysis

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17  # SonarScanner requires Java 17
          distribution: 'temurin'

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          scanner-version: 5.0.1.3006  # Update to newer scanner version
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
