rname: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          # CORRECT PARAMETER NAME (camelCase)
          scannerVersion: 5.0.1.3006
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Verify Connectivity
        run: |
          curl -I -X GET "${{ secrets.SONAR_HOST_URL }}/api/server/version" \
          -H "Authorization: Bearer ${{ secrets.SONAR_TOKEN }}"
